name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"

      - name: Build app
        run: scripts/buildprod.sh

      - name: Login to Github container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ghcr.io/amirkhaidir/notely:latest

      - name: Push image to Github container registry
        run: docker push ghcr.io/amirkhaidir/notely:latest